[package]
name = "orderbook"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
serde = {version = "1.0.228" , features = ["derive"]}
serde_json = "1.0.149"
actix-cors = "0.7"
actix = "0.13"
actix-web-actors = "4"
rand = "0.8"

